#206 add quality attribute for YustImagePicker
janneskoehler/yust pull request #32
Opened 2021-06-14 12:52 UTC by speydril

2021-06-22 20:27 UTC, janneskoehler requested changes

2021-06-22 20:27 UTC, janneskoehler commented on lib/widgets/yust_image_picker.dart
>              .getImage(source: imageSource, maxHeight: 800, maxWidth: 800);
Das Problem ist, dass die Bilder mit maxHeight und maxWidth 800 bereits jetzt zu schlecht aufgelöst sind. Teilweise brauchen wir eine bessere Auflösung. z.B. 800 und 50 Quality für low, 1200 und 75 für Medium und 2000 und 100 für high.

2021-06-23 12:09 UTC, speydril commented on lib/widgets/yust_image_picker.dart
>              .getImage(source: imageSource, maxHeight: 800, maxWidth: 800);
Ich habe jetzt, das YustImageQuality Dictionary erweitert um die Eigenschaft 'size'. Ich bin mir nicht ganz sicher, ob ich das so schön gelöst habe, also sag mir ruhig, wenn es nochmal anders machen soll

2021-06-23 15:05 UTC, janneskoehler approved these changes

2021-06-23 15:05 UTC, merged