Download images in image screen
janneskoehler/yust pull request #61
Opened 2021-10-17 14:03 UTC by speydril

2021-10-30 12:34 UTC, speydril commented
@janneskoehler changes applied

2021-11-19 10:38 UTC, janneskoehler requested changes
Ein paar Dinge sind noch unrund. Siehe Kommentare im Quellcode.

2021-11-25 21:46 UTC, speydril commented
@janneskoehler changes applied now

2021-11-26 07:57 UTC, janneskoehler requested changes
![Bildschirmaufnahme 2021-11-26 um 08 55 24](https://user-images.githubusercontent.com/839271/143546541-c76c939f-e756-4b75-8867-587073bcfc86.gif)

Der Download funktioniert auf einem iPad leider noch nicht.

2021-11-26 08:21 UTC, speydril commented
> ![Bildschirmaufnahme 2021-11-26 um 08 55 24](https://user-images.githubusercontent.com/839271/143546541-c76c939f-e756-4b75-8867-587073bcfc86.gif)
> 
> Der Download funktioniert auf einem iPad leider noch nicht.

Hast du eine Fehlermeldung bekommen oder so ? Ich kann das für iOS leider nicht testen, aber für mein Android Tablet hats funktioniert

2021-11-26 13:45 UTC, speydril commented
@janneskoehler Ich habe es mit Jannis jetzt auf iOS probiert, sollte jetzt alles klappen. Bei iOS muss man bei dem sharePackage immer eine shareOriginPosition mitgeben

2021-11-27 08:00 UTC, janneskoehler commented
Eine kleine Sache habe ich noch festgestellt. Wenn ein Foto heruntergeladen wird, wird der Detail-Screen beim Schließen nicht mehr angezeigt. (s. Video)

Außerdem wäre es schöner, wenn im Web ein Download Button statt ein Share Button angezeigt wird. Also einfach das Icon tauschen.

![Bildschirmaufnahme 2021-11-27 um 08 55 58](https://user-images.githubusercontent.com/839271/143673376-74e0abeb-f0c8-46b1-81d2-f688abadbb43.gif)

2021-11-27 08:01 UTC, janneskoehler requested changes
S. letzten Kommentar

2021-11-27 08:51 UTC, speydril commented
> Eine kleine Sache habe ich noch festgestellt. Wenn ein Foto heruntergeladen wird, wird der Detail-Screen beim Schließen nicht mehr angezeigt. (s. Video)
> 
> Außerdem wäre es schöner, wenn im Web ein Download Button statt ein Share Button angezeigt wird. Also einfach das Icon tauschen.
> 
> ![Bildschirmaufnahme 2021-11-27 um 08 55 58](https://user-images.githubusercontent.com/839271/143673376-74e0abeb-f0c8-46b1-81d2-f688abadbb43.gif)

Meintest du, dass du gern den Download Button gegen ein share button tauschen willst? Das Icon ist ja schon ein Download Icon.

2021-11-27 08:53 UTC, speydril commented
> > Eine kleine Sache habe ich noch festgestellt. Wenn ein Foto heruntergeladen wird, wird der Detail-Screen beim Schließen nicht mehr angezeigt. (s. Video)
> > Außerdem wäre es schöner, wenn im Web ein Download Button statt ein Share Button angezeigt wird. Also einfach das Icon tauschen.
> > ![Bildschirmaufnahme 2021-11-27 um 08 55 58](https://user-images.githubusercontent.com/839271/143673376-74e0abeb-f0c8-46b1-81d2-f688abadbb43.gif)
> 
> Meintest du, dass du gern den Download Button gegen ein share button tauschen willst? Das Icon ist ja schon ein Download Icon.

@janneskoehler kriegst du eigentlich auch schon eine Nachricht, wenn ich dich nicht mit @ erwähne?

2021-11-27 09:18 UTC, janneskoehler commented
Ups, ignoriere den Kommentar.

An ***@***.***> schrieb am Sa. 27. Nov. 2021 um 09:54:

> Eine kleine Sache habe ich noch festgestellt. Wenn ein Foto
> heruntergeladen wird, wird der Detail-Screen beim Schließen nicht mehr
> angezeigt. (s. Video)
> Außerdem wäre es schöner, wenn im Web ein Download Button statt ein Share
> Button angezeigt wird. Also einfach das Icon tauschen.
> [image: Bildschirmaufnahme 2021-11-27 um 08 55 58]
> <https://user-images.githubusercontent.com/839271/143673376-74e0abeb-f0c8-46b1-81d2-f688abadbb43.gif>
>
> Meintest du, dass du gern den Download Button gegen ein share button
> tauschen willst? Das Icon ist ja schon ein Download Icon.
>
> @janneskoehler <https://github.com/janneskoehler> kriegst du eigentlich
> auch schon eine Nachricht, wenn ich dich nicht mit @ erwähne?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/janneskoehler/yust/pull/61#issuecomment-980526959>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGM4ZYKTXPTYR6R6Y2A2F3UOCMDBANCNFSM5GE3LUDQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-27 13:14 UTC, speydril commented
@janneskoehler changes applied

2021-11-28 08:44 UTC, janneskoehler requested changes
Moin An. Ich bin immer noch nicht glücklich damit.

Erstens sieht der Übergang, wenn man auf das Bild klickt statt auf das X, deutlich besser aus:

![Bildschirmaufnahme 2021-11-28 um 09 33 17](https://user-images.githubusercontent.com/839271/143735446-e56a4cd0-d496-4eb2-9523-a365125f5d9c.gif)

Und zweitens ist der Zurück Weg über das Bild immer noch kaputt, wenn das Bild erst heruntergeladen wird.

![Bildschirmaufnahme 2021-11-28 um 09 37 26](https://user-images.githubusercontent.com/839271/143735600-ba884783-ba63-4adf-b589-9673ba20f94d.gif)

Wir müssen uns mal überlegen wie wir Bilder sauber ohne viel Quellcode herunterladen können. Im Moment behelfen sich die Leute mit Rechtsklick auf das Bild und dann speichern unter. Muss also nicht mit ins Release.

2021-11-29 18:55 UTC, speydril commented
@janneskoehler changes sind applied. Ich habe noch einmal ein paar Änderungen in Univelop gemacht. Das Problem ist das HTML gewesen, was dafür gesorgt hat, dass sich alles nochmal gerendert hat. In dem Moment baut sich dann der RecordListScreen neu auf und holt sich die URI, die zu dem Zeitpunkt aber gerade noch auf /imageScreen ist. Die Lösung war es jetzt den Record nur neu zu laden, wenn die uri mit "/record" beginnt (siehe DevOps) PR

2021-12-10 11:48 UTC, janneskoehler approved these changes

2021-12-10 11:48 UTC, merged