Redesign input fields
janneskoehler/yust pull request #74
Opened 2021-12-10 18:48 UTC by CLNMR

2021-12-20 04:05 UTC, janneskoehler requested changes

2021-12-20 07:43 UTC, CLNMR commented on lib/widgets/yust_list_tile.dart
> +      return Text('Anderer Style');
Ja, hab ich geändert :) Tatsächlich wird derzeit nirgendwo was anderes als YustInputStyle.normal verwendet (um das direkt zu sehen, hatte ich das so geändert), aber ich hab das jetzt trotzdem dringelassen, sodass auch eine OutlineBorder gezeichnet werden kann.

2021-12-20 07:46 UTC, CLNMR commented on lib/widgets/yust_input_tile.dart
>  class YustInputTile extends StatelessWidget {
Naja, ich setze ja schon drei "Standardwerte" (readOnly, showSelected, onDelete wird unfocus aufgerufen), die damit abstrahiert werden. Zudem finde ich auch den Code lesbarer, wenn du direkt siehst, dass ein YustInputTile verwendet wird, und nicht ein YustTextField, wo du dann nochmal schauen musst, ob dieses sich überhaupt wie ein TextField "verhält". Aber ich lass mich auch gerne überzeugen, wenn dir zB die Größe der Code-Base wirklich wichtig ist :) Meine persönliche Einschätzung wäre, dass es so tatsächlich _weniger_ Aufwand wäre, den Code zu pflegen, aber das ist vermutlich auch ein Stück weit eine philosophische Frage :)

2021-12-23 05:16 UTC, janneskoehler approved these changes

2021-12-23 05:19 UTC, merged